[preferred]
default=hyprland;gtk
org.freedesktop.impl.portal.Settings=hyprland;gtk
org.freedesktop.impl.portal.AppChooser=hyprland;gtk
org.freedesktop.impl.portal.Print=gtk
org.freedesktop.impl.portal.FileChooser=gtk
org.freedesktop.impl.portal.Screenshot=hyprland
org.freedesktop.impl.portal.Screencast=hyprland
